language: python
python:
- '3.6'
install:
- pip install -e .[test,ci]
script:
- pytest --cov=fbroadrunner --cov-report annotate
deploy:
  provider: pypi
  user: marcelomoraes28
  password: $PIP_PASSWORD
  on:
    tags: true
    branch: master
    python: '3.6'
after_success:
- coveralls
