language: python
python:
- '3.6'
install:
- pip install -e .[test,ci]
script:
- pytest --cov=fbroadrunner --cov-report annotate
deploy:
  provider: pypi
  user: marcelomoraes28
  password:
    secure: bYzjZjQu2zxIS3XM7L8cX1RPdk3APr1JFh7qB1FK0pTd1jPOK+UoYat0dg57yOqjREV1yyugXk/aMS3laiAC4YbJtFYaUjU2HXl4TZz0SdFtluGNYGHLsnmOtT1J3NfBQ4j2ne8wb9QsZfsZEY3LKpo77734EjeqiWZwE88H4Ie3rAF86rKXlcBQGxz44dQjsSwfaLpxUun6lbENgPVg6HS6lbOK9m7vO06NbD9pfnHSkhEHn68MJLTdrDctA2QaMV+5aojP1A7G5D4E5VD0ZOTHhPlt7YPQoGWieqkAhGfnCpOWmA+pqnHCFjasjwCfZzERaOxBTf9zuA4ByYAA243glriVX1QGAeMcwccF5mCGCiWUAKDBce0P+iRt4Nb5Gi2uPBWZdzWw3eC/v3/hyaZmcVp4XT9PtUS23APqTxNSkebDF25lIA4OF/VAm3K4flR+YDZ/D7U0DzjRwpsLmIN86zqla3w19CzgyP3J24BeipPPGfK47tDdpIkPIQxqsOHVRblUSobrVCng0/xcW616CUhWNwY6vafKcPTWw+Whgb092FDpBewI7PmesV957nmbmfUsuDwAUdOEEjNFYIFkpdnszt0xLbZmAMnarlFR1yYMWbGgVOcHXqXFd1OgYMTDdQXJlJx3Rqtp7RYf0g+ezZTDwyExt75KMoIkig0=


  on:
    tags: true
    branch: master
    python: '3.6'
after_success:
- coveralls
