language: python
python:
- '3.6'
install:
- pip install -e .[test,ci]
script:
- pytest --cov=fbroadrunner --cov-report annotate
deploy:
  provider: pypi
  user: marcelomoraes28
  password:
    secure: ZVZUr3rZoVt9ptXybEzhwb6wP5lePKNCQAx7A3aoWO13Q7/Ue0hEtxzVYN2xVN9UmwgcMR5eT3uc7LAL2pssk8EmNkxrYTvvgjBTlXezTMitMNZ2f3wsPqJq6S0vpY3Cb44ib8ANI+MUDhFOIiWl/TdY+punHDr1AmsM3pSF/z7AYPw3Fib7teIzMHC+kENLI/T6VAc307VzAxrO3TgQyW5oNOH0fhB/PFfhQqmIQyArIrWhbaxlv9f/NR9cJUzeEE+GCDW5PkkY0uLwlTm6bAAC5PeR4xH7zZDD4r/3+BWfj8lWEcYRHM07kYdPao/fnq3N4po4DUdXCbmOx927sUlnQTzNhT2oDAj3MgE6eNx5r+/JXwtaUhWTtiR4qiQaSwHJyUvLRLgvO4o9JOFYSdZVV5aFzIuH7ABd+N8h8aIEkW4nxFdaSDw/cpr26TA4WhQL6LoBwOWbBV3ognHMt4tey+n6tucpsl5hfWWniFVGZSu0bDX3e34s+nEq7fdofEVXxYMZRta48FBwnsjGi4m2oCzhn8i/sfz+bGCQU/YmHCh7663jodTiF9JGJ3Nl6wJ53uxmQuwN/3jdO1sYbqyZINK853qtAd3Zn/nXhlDNfGu3wbJGYNN8zKB2jTR5KDkEtzrBiJgWMPmzJYX43mLkooHAIeAQ9NdAEcLGPiY=
  on:
    tags: true
    branch: master
    python: '3.6'
after_success:
- coveralls
