language: python
python:
- '3.6'
install:
- pip install -e .[test,ci]
script:
- pytest --cov=fbroadrunner --cov-report annotate
deploy:
  provider: pypi
  user: marcelomoraes28
  password:
    secure: CotA//nA+4ae4E2RXhjOR09vgO1JZjAVxXqvEepve8mOWo+JqLAKsx7UOKJNcSRuA4ffVZli0eZ1rrApXlLX8ZWET5CbIghZEj285eIQ0zXj+GUP0YYfCDtkWWqpRG+rZafyNBMsrOilHBh8R4rh30Q2XtNtg7IQnd4edTk53UAOjZlLTJdLT2BWsGHg9Ywmnxb+z9QE4ZGKyV7Tft2b51IIqpRpHx6WVbw7PHz/j02SiBHXzKB1OAevqy00X6DF9E9S0jScMpA51wzRJAgBb9eWNuZwY+TfGLUhWhdFva9MRhf4mMCAHsUSQxhirMaLq/6A0L85Bhb3L7QM5NbsFEc8fhw30qP3b9HLkBeHe76WubvUoZhAB4SvneV0rw6c6+GovK2hhAyMOoXS12i630DM+MeAKJftp516Y4RSpNaBgJ4pC+MZiowdDcKgHYJQY45N/HV5d5PTroJm3GRdswVy/vk+swOrjRtounBGjo5HjryxCarQHJNyo/f2lCPTx3qCVSXEjX8bjYyeH2jQH294qYQHaE2/HecUi+eQQuMXgX8l3fLj1ykasbujbem4sP6Pg4TmTyD1Gm174b0fnKZvFe+E7rY/ygG0/wlcseCmsa2HlNP/2aIBQsdHGG/kq738hlX8mzGEpl/pr+hkU3FKnZtiK/T0tEcR7ETEpus=
  on:
    tags: true
    branch: master
    python: '3.6'
after_success:
- coveralls
