language: python
python:
- '3.6'
install:
- pip install -e .[test,ci]
script:
- pytest --cov=fbroadrunner --cov-report annotate
deploy:
  provider: pypi
  user: marcelomoraes28
  password:
    secure: PLYepNIKWx4yMvfEEWox2puRtFLcytEFyjIbKCYYsmHuve5TPK7l0jC+ZeGK+NshAPmbjjUBNdQQ2GIJk99wLnKxb6CCoFQlTLSdDG0G/Kc2JT5NUn/g26jJ05z4x/hXyAxBLYCsm3p7cXQjWkCVn+Qts8H18Jca52yKHkhmyRZGSjVoWSNkshmW5kcnPUo0sUsFJx0U+jlEGuK3dYVkLNkoPSUJDYEdMd8+LZCe1EXYPjn53wvNjb2mnvIhdr1qbvbP9iC/DZr1iACsDJbX6IK9XVPv5Nv7YjB8aG9M1/3gxfb8CIygBTECCtNEc2mIg99mXgVKKlYOlFybIKeC4ATaZlkZePdfG1lzDMkhWcZoLtSu/7lftjVFb6OKXMIsibik6cHSUxn8sC6T/ktwIrPACWs364s/RKBX5Nwdc32atUHP7YmFBIaLuCufg7XBtty4VWB6XFR1+NzixGdXlyRGunfhUD9sc4uKOOTv9DqjP1GWIE6uzxT7pRkWTiyuhQOOB5Hb72gTlmbiIOYKmTFDGoVcuE0hz/eEfRewiOfqSHnPZLo2ADITM2ECOSTjWeb3B2arvtRYR+axOmTKkEsf55A3sP/boKPNO8r8ZPu3Le30CH0/mHXfFbovPVMpJwlhDINaPwvBVPyiq/wheI5iJGHpy+nCOtY2D8tuyhE=
  on:
    tags: true
    branch: master
    python: '3.6'
after_success:
- coveralls
